export {
  gatewayKeys,
  useGateways,
  useGateway,
  useGatewayHealth,
  usePromotions,
  usePromotionTargets,
  useCreatePromotion,
  useUpdatePromotion,
  useScalingPolicies,
  useCreateScalingPolicy,
  useUpdateScalingPolicy,
  useDeleteScalingPolicy,
  useScalingEvents,
  useManualScale,
} from "./useGateways";
